### ISSUE TITLE
Enable precompiled headers in docker image

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#1]
As of https://github.com/WardBrian/tinystan/commit/6688eb70e18b0e6911e4fac3988309bfc5c2ec73, the following added to `make/local` should result in faster compile times:

```makefile
CXX_TYPE=clang # Stan's auto-detection isn't smart enough for em++
PRECOMPILED_HEADERS=true
```

**Comment by magland** [comment]
@WardBrian 

I confirm that the compilation time has decreased from 18 seconds down to 13 seconds for the basic example.

The new version has been pushed to dockerhub, but it is not yet loaded on the public server. I'll do that soon.

**Comment by magland** [comment]
New image now loaded on public server, and it reliably gives 13.5 seconds for basic example

**Comment by WardBrian** [comment]
Some other tricks we might want to try are not passing `-g`, and setting `-DCMAKE_BUILD_TYPE=Release` in the TBB cmake step (the default is RelWithDebug, which builds larger objects that might be slower to process downstream)

Both of these things would also make the generated code less debuggable, so they should probably be done much later in the lifecycle.
