### ISSUE TITLE
Encapsulate string/error-parsing logic from StanFileEditor.tsx

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/stan-playground#105]
A lot of the logic for parsing error messages from stanc is currently located in the editor front-end component. I believe it would be more robust to put it in a separate file or closer to the stanc interface.

**Comment by WardBrian** [comment]
I can tackle this. It should be pretty easy for me to write some tests that generate some of the odder types of locations that can occur in a Stan program.
