### ISSUE TITLE
Formatter and linter for the frontend

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#107]
I think at least a few of the recent merge conflicts we've had on PRs have been due to formatting differences between editors rather than actual content changing. It would be nice to have a consistent style we can all just tell our editor to use and then forget about it.

I don't have a super strong opinion on which, but to make this concrete I would suggest [Prettier](https://prettier.io/) with a minimal config. For Stan-Web-Demo I used
```json
{
  "tabWidth": 2,
  "semi": true,
  "arrowParens": "avoid"
}
```

**Comment by magland** [comment]
Sounds good. Shall we try to get to a place where we have no outstanding PRs and then sweep through the code and (a) change Analysis to Project (b) enforce prettier formatting?

**Comment by WardBrian** [comment]
I think it would be beneficial to do it earlier (at least before the webr/pyodide stuff gets merged)

Right now is probably the fewest outstanding PRs we’ve had in a while, especially if we merge #102 and #97 today, so I would propose doing it ~now

**Comment by magland** [comment]
Cool. Once those two are merged (from my perspective they are ready to go), could you make a utility script that formats all .ts/.tsx files, and then we can review whether that is suitable? Do we want to have a pre commit hook? CI check? VSCode setting?

**Comment by WardBrian** [comment]
We already have pre-commit on the backend — that seems like a good choice locally, but setting up your VSCode can also help obviously. 

I will update our config and run the full format after they’re merged

**Comment by magland** [comment]
Sounds good... I snuck one more in there #108 which I think could be merged right away.
