### ISSUE TITLE
Main bundle size

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#109]
I noticed just now that `yarn build` is reporting that index.js is over 2MB now. It appears this is primarily due to #100, which is now pulling in much more of the monaco editor -- without those changes, it is ~500kb

**Comment by magland** [comment]
I personally think the squiggles are worth it. But we could also try to lazy load.

**Comment by jsoules** [comment]
I'm not fussed for the moment, but we'll probably want to look into a slimmer version of the package at some point.

If not, maybe that's just the price of getting a full-featured Stan compiler and IDE in your web browser :p
