### ISSUE TITLE
Integrate analysis.py/analysis.R into UI

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#119]
Compliment of #104 

My proposal is something like this:

- Flatten out the controls for sampling and push them to the top of the right panel
- Two tabs. One is all the existing content/ "pre-computed" analysis, the other is "Code"

![proposal](https://github.com/flatironinstitute/stan-playground/assets/31640292/5b5332b8-766c-4af7-849f-5e57195e9045)

**Comment by magland** [comment]
Could you clarify some more.

Tab 1 would be main.stan, data.json, sampling opts, sampling run button, and sampling outputs?

Tab 2 would be analysis.py and analysis.r which has the sampling outputs available as input?

What about data generation, data.py / data.r?

**Comment by WardBrian** [comment]
Sorry, that image is of only the right panel. So main.stan/data.json are to the left of this image offscreen

The sampling options/run button are at the top of the panel, and tab 1 is just the summary, traceplots, histograms we have now

**Comment by magland** [comment]
Okay so the left panel is always just main.stan and data.json?

Where is the data.py/data.r?

In your "plot outputs" that is just the outputs of analysis.py/.r, correct?

Two columns in the right panel seems like a lot. I wonder if the analysis/code should be a tab that covers up the main.stan and data.json, to have more horizontal space.

**Comment by WardBrian** [comment]
I'm assuming data.py/data.r either live entirely in the left column, or they cover up this panel in a fly-in/fly-out style.

I think keeping at least the model in view at all times is useful. 

Correct, it is the plots from R/Python. The second column can (should?) probably just wrap to be below the stdout/stderr on smaller screens. I think that wouldn't be too hard with MaterialUI's Grid, since it has reactive CSS by default

**Comment by magland** [comment]
I can take a crack at the second analysis/code tab tomorrow, unless someone else wants to.
