### ISSUE TITLE
Allow partial parse for SamplingOpts

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/stan-playground#125]
As mentioned in comments for PR #124 

Currently we insist on a full parse for a `SamplingOpts` object to be considered successfully deserialized. Going forward it will likely be more resilient and flexible to populate any missing values with defaults instead.

**Comment by WardBrian** [comment]
In particular, this issue should be considered a blocker for adding any new entries to SamplingOptions. Before that point, it's just a "nice to have"
