### ISSUE TITLE
data and analysis script examples available to user

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#149]
I think it would be helpful for there to be a "?" icon at the top of the editors that would show documentation for writing the analysis.* and data.* scripts. Otherwise, I think a user wouldn't know how to get started when opening these tabs. I think this should be in the form of a markdown document that is opened as a popup window. I have some react components that can render markdown, including code snippets. But to start we could also just link to docs on github containing examples.

Let me know if you want me to get started on this.

**Comment by WardBrian** [comment]
I think we should probably update the default values for these files to be a comment explaining them, rather than them defaulting to empty. That should be more than sufficient for the data ones, at least. Analysis scripts may need something closer to what you describe to fully explain them

**Comment by magland** [comment]
> I think we should probably update the default values for these files to be a comment explaining them, rather than them defaulting to empty. That should be more than sufficient for the data ones, at least. Analysis scripts may need something closer to what you describe to fully explain them

I don't like the idea of every saved project having comment-only files called data.py, data.R, etc. I think they should be empty if not used, so they don't get included in the export

**Comment by WardBrian** [comment]
That’s a fair point. We could update the export logic to check if they’re different from their defaults AND nonempty before including them, if we wanted. 

I think some users will honestly miss the ? — I hadn’t really taken note myself

**Comment by magland** [comment]
How about, if the editor is empty, then display a special noticeable message in the toolbar: GET STARTED or something. If not empty, then it's just a "?" icon.

**Comment by magland** [comment]
That's a cool idea. Let me take a crack at that for the stan editor.

**Comment by magland** [comment]
... unless you already started.
