### ISSUE TITLE
Control parameters for sampling

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#16]
The following would be nice to have control over:

- [ ]Number of chains (default 4, in practice I think this being a slider from 1 to 8 is probably reasonable, but in theory it can be unbounded)
- [ ] Number of warmup iterations (default 1000, can be [0, $\infty$)) 
- [ ] Number of sampling iterations (default 1000, can be [1, $\infty$))
- [ ] Initializations. This is tricky, can either be 1 json object or a list of num_chains JSON objects.
- [ ] "Initialization radius" (parameters not given an initial value directly are drawn from `uniform(-R, R)` on the unconstrained scale) (default 2.0, can be [0, $\infty$), but in practice limiting to say 10 in the UI is probably fine)
- [ ] Seed. Any uint32.

There are also these, which are more advanced and might belong on a drop down/panel that is hidden by default

- [ ] Metric - decide which form of mass matrix to use. (Default is Diagonal. The set {Diagonal, Dense, Unit})
- [ ] save_warmup: whether the warmup draws are also returned in the output.
- [ ] stepsize: initial stepsize for the sampler
- [ ] adapt: (bool, whether to enable adaptation)
- [ ] delta: target acceptance probability for the dual averaging adaptation
- [ ] max_depth: maximum tree depth allowed for the sampler (# of evals can be on the order of 2^{max_depth}, so be careful)

The rest are probably not priorities, and if they are supported should be grouped with the more advanced options.

**Comment by magland** [comment]
I assigned this to myself.
