### ISSUE TITLE
Sporadic unexpected page reload

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/stan-playground#166]
Not sure if this is an issue with the code or just something weird on my machine since I can't reproduce consistently, but I've seen it come up a couple times now.

Rough steps to reproduce:

- Start with cold cache (first load of Stan-Playground, at least in a bit)
- (Optional) make minor change to main.stan without saving
- Run sampler; wait for sampling to complete
- Open Analysis.py tab, wait ~20 seconds
- Note unexpected page reload (which erases any unsaved changes in other windows)

Maybe has something to do with the delayed loading of the analysis worker thread? In any event, just something to keep our eyes open for since I can't reproduce consistently at this point.

**Comment by WardBrian** [comment]
Are you able to reproduce this on the actual production site? I have gotten this with `yarn dev` but usually accompanied with a message from vite about re-optimizing dependencies.

**Comment by magland** [comment]
> Are you able to reproduce this on the actual production site? I have gotten this with `yarn dev` but usually accompanied with a message from vite about re-optimizing dependencies.

Same for me

**Comment by jsoules** [comment]
Haven't been looking at production--so haven't noticed. I'll see if I can reproduce there, but this was meant more as a heads-up anyway.

**Comment by WardBrian** [comment]
I'm pretty sure the config change in #182 will prevent this, do re-open if it keeps occuring!
