### ISSUE TITLE
increase left panel width slightly

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#183]
The left panel width needs to be increased slightly to prevent the horizontal scroll bar from appearing. (We could disable horizontal scrolling, but I don't think that's the right approach because in the future we may have longer titles of examples)

![image](https://github.com/user-attachments/assets/aaeb1639-3d5a-4aea-870b-ef4a9a84371b)

**Comment by WardBrian** [comment]
I believe this is an artifact of the `margin`s in the CSS. Putting `overflow: hidden` on `.Sidebar` does make it go away, though it would need adjusting if we ever wanted longer titles
