### ISSUE TITLE
do not show scrollbar in editor toolbar

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#199]
When width is very small the editor toolbar shows a scrollbar which I don't think is appropriate.

![image](https://github.com/user-attachments/assets/671ce5e0-42bc-4166-9385-a8a4e44354e7)

**Comment by WardBrian** [comment]
This is the only place we display errors from the backend server, and it is nice for small screens, so I would like to keep it

**Comment by magland** [comment]
Okay
