### ISSUE TITLE
If a model has too many parameters, opening the "Histograms" tab can freeze the UI

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#201]
Possibly worth truncating at some value (say ~50), and adding a "show more" button to the bottom, similar to the draws table.

**Comment by magland** [comment]
I can work on this... but wondering if you could provide a project link for this case if not too much trouble?

**Comment by WardBrian** [comment]
This is where I observed it myself: [inhalers](https://stan-playground.flatironinstitute.org/?title=Bugs%20Examples%20-%20Vol1%20-%20Inhalers%20-%20Inhalers&stan=https://raw.githubusercontent.com/stan-dev/example-models/master/bugs_examples/vol1/inhalers/inhalers.stan&data=https://raw.githubusercontent.com/stan-dev/example-models/master/bugs_examples/vol1/inhalers/inhalers.data.json)

the model takes some time to sample with the defaults, but if you set it to 10 warmup/10 sampling you can still notice the freezing on the tab
