### ISSUE TITLE
Backend: make compilation async

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#25]
See https://docs.python.org/3/library/asyncio-subprocess.html

This should be an easy way to improve throughput on the server side

**Comment by jsoules** [comment]
Great. Yes I was looking at this earlier & should be able to add it to the backend refactor (branch is already up if you want to take a look or I’ll put in a PR on Thursday)On May 21, 2024, at 15:40, Brian Ward ***@***.***> wrote:﻿
See https://docs.python.org/3/library/asyncio-subprocess.html
This should be an easy way to improve throughput on the server side

**Comment by magland** [comment]
@jsoules Regarding the backend refactor, I have been making some small changes to the server code and so we're going to get conflicts. Will need to handle those carefully.

Could you make a PR for your branch, even if it's a [WIP]?

**Comment by WardBrian** [comment]
Because we're not passing `--workers` to uvicorn, I'm observing that right now the fact that the subprocess is blocking actually means you can never serve more than one compilation request at a time

Especially since a lot of #28 is based around the concerns of locking for multi-threaded situations, perhaps we could add `--workers 4` in run.sh?

**Comment by jsoules** [comment]
> Especially since a lot of https://github.com/flatironinstitute/stan-playground/pull/28 is based around the concerns of locking for multi-threaded situations, perhaps we could add `--workers 4` in run.sh?

I'd been assuming that was a near-term next step, but happy to do it now :smile:

**Comment by magland** [comment]
Sounds good to me.
