### ISSUE TITLE
non-blocking sampling - need report progress and enable canceling

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#3]
@WardBrian 

Would be great if we could expose a lower level entry point into tinystan so that we can perform sampling in a non-blocking manner and provide real-time updates to the user. Right now the full sampling is done in a single blocking call to `_tinystan_sample`

Alternatively could we get a callback from _tinystan_sample with the progress? And perhaps if the callback returns false, then it cancels the sampler?

Would be great to be able to hook into mcmc monitor.

**Comment by WardBrian** [comment]
I will have to think about this. 

I'm not immediately clear on what you mean by a lower-level entry point. Ultimately Stan implements its inference algorithms as fairly monolithic blocking calls, so my first reading is what you're asking for can't be done internally to tinystan. 


Re: callbacks - 

Stan does natively support a "interrupt" callback. It's what allows `Ctrl+C` to work inside the algorithms (see [tinystan/src/interrupts.hpp](https://github.com/WardBrian/tinystan/blob/main/src/interrupts.hpp)). I could have the option to supply one from the outside in environments like this were the default interrupt handler does not make sense.
This callback is called regularly, so it would need to be fast, and it does not receive the current iteration number.

Honestly, so far as I can tell, most progress bars in the Stan ecosystem are based around observing the output text from the sampler, e.g. the stuff currently ending up in the console: ` Chain [4] Iteration: 1000 / 2000 [ 50%]  (Warmup)`
Here's where `cmdstanpy` matches that: https://github.com/stan-dev/cmdstanpy/blob/cbea79f3e2f03dfe0f056c30cb613bf30d527750/cmdstanpy/model.py#L2140 

The second argument to the `StanModel.load` interface (currently `null` in this codebase) is a callback which redirects the output currently going to console.log. For stan-web-demo I implemented this in a way where it soaks up all the output for a run and then calls it, but this was probably over-specialization and real time streaming is a better default.

**Comment by magland** [comment]
Okay I need to understand the StanModel.ts better. If you have a chance could you stop by so I can ask some questions about what's happening there?

**Comment by magland** [comment]
@WardBrian I did some more testing, and it seems that in order to cancel and update progress on the page, it's going to be necessary to get this into a worker thread, and I think that means we're going to need to change what gets output as .js and .wasm from the compiler. It needs to be suitable for a worker thread. This is too bad since the current .js and .wasm worked so seamlessly. We'll need to discuss.

**Comment by magland** [comment]
An alternative would be something like this

https://emscripten.org/docs/porting/asyncify.html

**Comment by WardBrian** [comment]
My reading of the asyncify page is it requires inserting things like `emscripten_sleep()` into the core loops to actually get it to yield, which is not really an option.

`em++` does support a --proxy-to-worker flag, but I don't fully understand it's usage.

**Comment by WardBrian** [comment]
I think `--proxy-to-worker` is not ideal.

I've seen several suggestions along the lines of "load your wasm module on the main thread and then ship it over". There are several linked here: https://producement.com/development/using-emscripten-webassembly-in-web-workers-and-interacting-with-native-c-c-code-concurrently/

There are flags `--pre-js` and `--post-js` which will insert javascript code before or after the module definition in the generated .js from emscripten. I would be very hesitant to do anything more custom than that, since it would almost certainly break from version to version

**Comment by magland** [comment]
I tried a couple things, and I think we'll be able to achieve what we need by popping up a new window on the same domain that shows progress and allows to cancel. I'll work on that next week.

**Comment by WardBrian** [comment]
I have a branch at https://github.com/flatironinstitute/stan-playground/tree/worker-thread which moved the sampling off the main thread. It still needs some work to receive the messages back, and it was being done at the same time as your changes to try to report progress so those will need to be given a fresh look after it’s ready

**Comment by magland** [comment]
@WardBrian I think what you are trying here is the right approach, if it can work. I gave this a shot but got stuck with the worker thread not supporting "import" and other features of the code generated by the compilation server. Were you able to confirm that the worker actually is able to run without error?

**Comment by WardBrian** [comment]
yes, it samples and the UI in the main thread stays responsive. Right now the only way to see the result is in the console but that’s “easy” to fix, I think. I will pick up where I left on on probably Tuesday

**Comment by magland** [comment]
This is amazing!

I think it would be good to encapsulate the worker interaction into an interface class. Something like this

```typescript
import StanWorker from '../tinystan/worker?worker';

type Progress = {
    current: number
    total: number
    // etc
}

class Sampler {
    #isSampling: boolean;
    #onProgress: ((progress: Progress) => void) | undefined;
    constructor(private d: {worker: StanWorker}) {
        this.#isSampling = false;
        // receive messages from worker
        this.d.worker.onMessage((msg: any) => {
            if (msg.type === 'progress') {
                this.#onProgress && this.#onProgress(msg.progress);
            }
        })
    }
    static async create(o: {data: any, compiledModelUrl: string}) {
        const worker = new StanWorker();
        await this.sendRequest({
            type: 'init',
            compiledModelUrl: o.compiledModelUrl,
            data: o.data
        })
        const sampler = new Sampler({worker});
        return sampler;
    }
    async startSampling(onProgress: (progress: Progress) => void) {
        if (this.#isSampling) {
            throw new Error('Sampling already in progress');
        }
        this.#onProgress = onProgress;
        this.#isSampling = true;
        await this.#worker.sendRequest({type: 'startSampling'});
    }
}
```

I started working on that, but then thought I should let you finish up what you started.
