### ISSUE TITLE
Backend: App settings

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#33]
See [Settings and Environment Variables](https://fastapi.tiangolo.com/advanced/settings/#settings-and-environment-variables) in the FastAPI docs

We currently have the following items either hardcoded or using environment variables:

- `SWS_PASSCODE`
- `BASE_JOB_DIR`
- `COMPILED_MODELS_BASE_PATH`
- `COMPILATION_TIMEOUT`
- `TINYSTAN_DIR`

Additionally, it would be nice to have a global `DEBUG` setting, and possibly gate the idea of canonicalizing models for cache purposes behind a feature flag, since there are known tradeoffs to doing so. 

Each of these being runtime configurable would also help with testing, see the FastAPI note on the subject: https://fastapi.tiangolo.com/advanced/settings/#settings-and-testing

**Comment by magland** [comment]
This sounds good to me.
