### ISSUE TITLE
updates on the UI

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#4]
@WardBrian @jsoules 

Just reporting some updates on the UI (gh discussions doesn't seem to be enabled on FI org)

* There's a public compilation server now
* User can select between public / local / custom (component in menu bar)
* Left panel contains a list of examples you can click on
* Ability to clear all browser data (good for testing)

Short term plans
* Cache some compilation info in browser so that you don't need to click "compile" each time page is reloaded

**Comment by WardBrian** [comment]
One early bug: if I compile a model, make changes to it, and save it, the rest of the UI doesn't reset to the model not yet being compiled (e.g. the Run button is still available, the green `compiled` text is shown next to the compile button)

**Comment by magland** [comment]
> One early bug: if I compile a model, make changes to it, and save it, the rest of the UI doesn't reset to the model not yet being compiled (e.g. the Run button is still available, the green `compiled` text is shown next to the compile button)

This has now been fixed.
