### ISSUE TITLE
Layout changes

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#59]
Supporting #57 and #58 will require us to be pickier about how we use our screen space.

Previously discussed changes:
- [ ] Make the sidebar collapsible, particularly to support viewing on smaller screens.
- [ ] Hide the syntax error window by default to save space (#51)
- [ ] Move the data panel to underneath the Stan model, freeing up the entire right panel for sampling + analysis (#45)

**Comment by magland** [comment]
This has been split out into #85 #86
