### ISSUE TITLE
Ability to upload local files

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/stan-playground#61]
Ideally both the zip files produced by #60 and also dragging individual files into the UI

**Comment by magland** [comment]
With #53 you can already upload some individual files (main.stan or data.json) but this replaces the entire project. For this issue, are you thinking of just uploading a stan file, for example, but keeping the rest of the project intact? In that case, I think there should be a small upload button on the stan file editor toolbar. Dragging a file into the editor window without clicking an upload button may also be possible, but it might be challenging.

**Comment by WardBrian** [comment]
I think it would be nice if dragging individual files only replaced those files. For example, dragging the stan file, then the data file, should have the same result as if I had highlighted both at the same time and dragged them as one 'unit', if that makes sense?

**Comment by magland** [comment]
> I think it would be nice if dragging individual files only replaced those files. For example, dragging the stan file, then the data file, should have the same result as if I had highlighted both at the same time and dragged them as one 'unit', if that makes sense?

Can we decide that the "Import" button from #53 always replaces the entire project? That would simplify things. Then we can provide separate intuitive mechanism for replacing individual files - not using the "import" button?

**Comment by WardBrian** [comment]
I like that - importing does imply a full project IMO, it's the drag/drop feature that would be nice to be more granular

**Comment by magland** [comment]
Done in #80 . closing
