### ISSUE TITLE
Simplify main-content component chain

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/stan-playground#78]
The current chain of components for spinning up the main application page is:

- entry point: `index.html`, which instantiates
- `main.tsx`, which renders
- `App.tsx`, which renders
- `MainWindow.tsx`, which renders
- `HomePage.tsx`, which (I believe) is currently the only page.

Call chains like this can get quite confusing, as it's not clear what each one is contributing; I hope we can combine several of these so that understanding how the app spins up doesn't require chasing through so many files. (By comparison, for QUASR/the Stellarator Navigator, I have `index.html` -> `main.tsx` which sets up routing, local cache, and CSS imports; then everything below that level is specific page components.)

**Comment by magland** [comment]
This sounds good to me. I was just using a template from a more complex application... but yeah, there's no reason to have so many "main" files.
