### ISSUE TITLE
Make the sidebar collapsible, particularly to support viewing on smaller screens.

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#86]
Split off from #59 

I'll start with detecting if width is too small and simply hide it. In future, we'll want to also have a button.

**Comment by WardBrian** [comment]
The material UI “drawer” component seems well suited to this https://mui.com/material-ui/react-drawer/

**Comment by jsoules** [comment]
I've used this component before (e.g. https://github.com/jsoules/stellarator-navigator/blob/trunk/stellarator-navigator/src/components/selectionControl/SelectionControlDrawer.tsx) and found it very convenient.

**Comment by magland** [comment]
I think those two solutions are probably best in terms of styling, but I wanted something where I'd have more control of the exact functionality and sizes... so I did this:
#88
