### ISSUE TITLE
type guard needed when loading from localStorage

### ISSUE THREAD

**Issue by magland** [flatironinstitute/stan-playground#89]
It's important to check that the state loaded from local browser storage conforms to the SPAnalysisDataModel type.

I ran into a problem where I had old content in my

```
const savedState = localStorage.getItem('stan-playground-saved-state')
```

And it caused the page to crash. I had to manually clear the local storage.

In `deserializeAnalysisFromLocalStorage` we should have a type guard instead of forced casting:

```
return intermediary as SPAnalysisDataModel
```

So we should do something like

```
if (!isSPAnalysisDataModel(intermediary)) {
  console.warn('...')
  return null
}
return intermediary
```

Then handle null appropriately.

**Comment by magland** [comment]
> I have read that typescript has deprecated the traditional “type guard” approach, but I’m not entirely clear on what it is they want us to do instead

Do you have a reference for that by chance? I use typescript type guards extensively.

**Comment by WardBrian** [comment]
I think I misread the text on the top of https://www.typescriptlang.org/docs/handbook/advanced-types.html -- it sounds like they have only deprecated _the documentation page of type guards_, at least the first one you hit from Google

**Comment by jsoules** [comment]
Right, but the "current version" of the documentation doesn't mention type guards anywhere.

It looks like it may just be a reorganization though--looks like this functionality is now under type narrowing in the current documentation (https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)
